version: '3'

services:
  drone-server:
    image: drone/drone:1.8.1
    ports:
      - 8000:80
    volumes:
      - ./data:/var/lib/drone
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    env_file:
      - ./conf/server.env
